In [12]:
from scipy.linalg import expm

In [2]:
import numpy as np                                          # 导入numpy库并简写为np
from mindquantum.core.gates import X, Y, Z, H, RX, RY, RZ,ZZ   # 导入量子门H, X, Y, Z, RX, RY, RZ
from mindquantum.simulator import Simulator    # 从mindquantum.simulator中导入Simulator类
from mindquantum.core.circuit import Circuit   


def Rz(t:float) ->np.array:
    return np.cos(t/2)*np.eye(2) - 1j*np.sin(t/2)*np.array([[1,0],
                                                      [0,-1]])
def Rx(t:float) ->np.array:
    return np.cos(t/2)*np.eye(2) - 1j*np.sin(t/2)*np.array([[0,1],
                                                      [1,0]])
def Ry(t:float) ->np.array:
    return np.cos(t/2)*np.eye(2) - 1j*np.sin(t/2)*np.array([[0,-1j],
                                                      [1j,-1]])

def Rzz(t:float) -> np.array:
    z = np.array([[1,0],
                  [0,-1]])
    return np.cos(t/2)*np.eye(4) - 1j*np.sin(t/2)*np.kron(z,z)
def Rzzz(t:float) -> np.array:
    z = np.array([[1,0],
                  [0,-1]])
    return np.cos(t/2)*np.eye(8) - 1j*np.sin(t/2)*np.kron(np.kron(z,z),z)

In [3]:
import numpy as np
from mindquantum import Circuit
from mindquantum.core.gates import RZ,ZZ, CNOT,H,RX
from mindquantum.simulator import Simulator    # 从mindquantum.simulator中导入Simulator类
from mindquantum.core.operators import Hamiltonian, QubitOperator
from tqdm import tqdm

In [4]:
beta_lst = np.linspace(0,2*np.pi,100)
gamma_lst = np.linspace(0,2*np.pi,100)


In [28]:

gamma = 2
beta = 1
#pbar = tqdm(total=len(beta_lst)*len(gamma_lst))
num_qubits = 4
sim = Simulator('mqvector', num_qubits)

In [140]:
circuit = Circuit()
circuit += Z.on(1)
circuit += Z.on(2)
circuit.matrix()

array([[ 1.+0.j,  0.+0.j, -0.+0.j, -0.+0.j, -0.+0.j, -0.+0.j,  0.-0.j,
         0.-0.j],
       [ 0.+0.j,  1.+0.j, -0.+0.j, -0.+0.j, -0.+0.j, -0.+0.j,  0.-0.j,
         0.-0.j],
       [ 0.+0.j,  0.+0.j, -1.+0.j, -0.+0.j, -0.+0.j, -0.+0.j,  0.-0.j,
         0.-0.j],
       [ 0.+0.j,  0.+0.j, -0.+0.j, -1.+0.j, -0.+0.j, -0.+0.j,  0.-0.j,
         0.-0.j],
       [ 0.+0.j,  0.+0.j, -0.+0.j, -0.+0.j, -1.+0.j, -0.+0.j,  0.-0.j,
         0.-0.j],
       [ 0.+0.j,  0.+0.j, -0.+0.j, -0.+0.j, -0.+0.j, -1.+0.j,  0.-0.j,
         0.-0.j],
       [ 0.+0.j,  0.+0.j, -0.+0.j, -0.+0.j, -0.+0.j, -0.+0.j,  1.-0.j,
         0.-0.j],
       [ 0.+0.j,  0.+0.j, -0.+0.j, -0.+0.j, -0.+0.j, -0.+0.j,  0.-0.j,
         1.-0.j]])

In [4]:
num_qubits = 4

sim = Simulator('mqvector', num_qubits)
beta_1 = 1
gamma_1 = 2
beta_2 = 3
gamma_2 = 4
num_qubits = 4
beta_1 = 1
gamma_1 = 2
circuit = Circuit()
for i in range(num_qubits):
    circuit += H.on(i)
for i in range(num_qubits):
    circuit += RX(beta_1).on(i)
for i in range(num_qubits):
    circuit += RZ(gamma_1).on(i)
circuit += ZZ(-gamma_1/2).on((0,1))
circuit += ZZ(gamma_1/2).on((2,3))
circuit += ZZ(gamma_1/2).on((0,2))
circuit.barrier()
circuit.svg()
#circuit.measure_all()      
#sim.apply_circuit(circuit)
#sim.sampling(circuit)
#sim.get_expectation(Hamiltonian(H_c))

In [5]:
t = np.array([1] + [0 for _ in range(15)]).reshape(-1,1)
B = circuit.matrix()
#B = np.around(np.transpose(B),4)
#t.reshape(1,-1).dot(B)
B

array([[ 0.18847556-1.64246650e-01j,  0.07091555+2.39731069e-01j,
         0.18847556-1.64246650e-01j,  0.13507558-2.10367746e-01j,
         0.13507558-2.10367746e-01j, -0.24749812-3.52800020e-02j,
         0.13507558-2.10367746e-01j,  0.13507558+2.10367746e-01j,
        -0.24749812-3.52800020e-02j,  0.13507558-2.10367746e-01j,
        -0.24749812-3.52800020e-02j, -0.24749812+3.52800020e-02j,
         0.13507558-2.10367746e-01j, -0.24749812-3.52800020e-02j,
         0.13507558-2.10367746e-01j,  0.13507558+2.10367746e-01j],
       [ 0.24004257+6.98538745e-02j,  0.16341091-1.89200624e-01j,
         0.24004257+6.98538745e-02j, -0.25      +0.00000000e+00j,
         0.25      -1.38777878e-17j,  0.10403671+2.27324357e-01j,
         0.25      -1.38777878e-17j,  0.10403671-2.27324357e-01j,
        -0.10403671-2.27324357e-01j, -0.25      +1.38777878e-17j,
        -0.10403671-2.27324357e-01j,  0.16341091+1.89200624e-01j,
         0.25      +0.00000000e+00j,  0.10403671+2.27324357e-01j,
         

In [20]:
from QAOA import _Rx,_Rz,_Rzz,_Rzzz,_Rzzzz,I,_H,getBaseProb

A = _Rz(0,4,gamma_1)*_Rzz(2,3,4,gamma_1)*_Rzz(0,2,4,gamma_1)  \
*(_Rzz(0,1,4,-gamma_1))*_Rz(1,4,gamma_1)*_Rz(2,4,gamma_1)*_Rz(3,4,gamma_1) \
*_Rx(0,4,beta_1)*_Rx(1,4,beta_1)*_Rx(2,4,beta_1)*_Rx(3,4,beta_1) \
*(_H() + _H() + _H() + _H()) #代表量子线路的矩阵
np.save("A.npy",A)

In [114]:
from QAOA import _Rx,_Rz,_Rzz,_Rzzz,_Rzzzz,I,_H,getBaseProb
A = (_Rzz(0,1,4,-gamma_1))  \
*_Rz(0,4,gamma_1)*_Rz(1,4,gamma_1)*_Rz(2,4,gamma_1)*_Rz(3,4,gamma_1) \
*_Rx(0,4,beta_1)*_Rx(1,4,beta_1)*_Rx(2,4,beta_1)*_Rx(3,4,beta_1) \
*(_H() + _H() + _H() + _H()) #代表量子线路的矩阵


In [43]:

(_Rzz(0,1,4,-gamma_1))*_Rzz(2,3,4,gamma_1)*_Rzz(0,2,4,gamma_1)  \
*_Rz(0,4,gamma_1)*_Rz(1,4,gamma_1)*_Rz(2,4,gamma_1)*_Rz(3,4,gamma_1) \
*_Rx(0,4,beta_1)*_Rx(1,4,beta_1)*_Rx(2,4,beta_1)*_Rx(3,4,beta_1) \
*(_H() + _H() + _H() + _H()) #代表量子线路的矩阵

PauliOperator([[ 0.18847556-1.64246650e-01j,  0.24004257+6.98538745e-02j,
                 0.24004257+6.98538745e-02j,  0.07091555+2.39731069e-01j,
                 0.24004257+6.98538745e-02j,  0.07091555+2.39731069e-01j,
                 0.07091555+2.39731069e-01j, -0.16341091+1.89200624e-01j,
                 0.24004257+6.98538745e-02j,  0.07091555+2.39731069e-01j,
                 0.07091555+2.39731069e-01j, -0.16341091+1.89200624e-01j,
                 0.07091555+2.39731069e-01j, -0.16341091+1.89200624e-01j,
                -0.16341091+1.89200624e-01j, -0.24749812-3.52800020e-02j],
               [-0.24749812-3.52800020e-02j,  0.10403671+2.27324357e-01j,
                -0.10403671-2.27324357e-01j, -0.13507558+2.10367746e-01j,
                -0.10403671-2.27324357e-01j, -0.13507558+2.10367746e-01j,
                 0.13507558-2.10367746e-01j, -0.25      -2.58818733e-18j,
                -0.10403671-2.27324357e-01j, -0.13507558+2.10367746e-01j,
                 0.13507558-2.1036774

In [ ]:
_Rx(0,4,beta_1)*_Rx(1,4,beta_1)*_Rx(2,4,beta_1)*_Rx(3,4,beta_1) \
*_Rz(0,4,gamma_1)*_Rz(1,4,gamma_1)*_Rz(2,4,gamma_1)*_Rz(3,4,gamma_1) \
*(-_Rzz(0,1,4,gamma_1))*_Rzz(2,3,4,gamma_1)*_Rzz(0,2,4,gamma_1)  \
*(_H() + _H() + _H() + _H()) #代表量子线路的矩阵

In [105]:
sim.reset()
t = sim.get_qs()
gamma = 3.123213
beta = 1.1223
circuit = Circuit()
circuit += H.on(0)
circuit += H.on(1)
circuit.barrier()
circuit += ZZ(gamma/2).on((0,1))
circuit += RZ(gamma).on(0)
circuit += RZ(gamma).on(1)
circuit.barrier()
circuit += RX(beta).on(0)
circuit += RX(beta).on(1)
A= circuit.matrix()
t.dot(A)
#C = QubitOperator('Z0 Z1') + QubitOperator('Z1') + QubitOperator('Z0')
#H_c = Hamiltonian(C)
#sim.apply_circuit(circuit)
#sim.get_expectation(H_c)

array([0.43935008+0.21253489j, 0.45244732+0.2209361j ,
       0.45244732+0.2209361j , 0.45772792+0.21270379j])

In [90]:
sim.reset()
C = QubitOperator('Z0 Z1') + QubitOperator('Z1') + QubitOperator('Z0')
H_c = Hamiltonian(C)
sim.apply_circuit(circuit)
sim.get_expectation(H_c)


(-0.3954560762156216+0j)

In [99]:
gamma = 2
beta = 1
A = _Rx(0,2,beta)*_Rx(1,2,beta)*_Rz(0,2,gamma)*(_Rz(1,2,gamma))*(_Rzz(0,1,2,gamma))*(_H() + _H())
A.dot(t)
C = QubitOperator('Z0 Z1') + QubitOperator('Z1') + QubitOperator('Z0')
H_C = C.matrix().toarray()
B = A.dot(t)
print(B)
np.conjugate(np.array(B)).dot(H_C).dot(np.array(B))

[-0.08927915-0.37837179j  0.29329455+0.32192467j  0.29329455+0.32192467j
  0.67586825+0.1129237j ]


(-0.3954560762156215+0j)

In [106]:
beta_lst = np.linspace(0,2*np.pi,200)
gamma_lst = np.linspace(0,2*np.pi,200)



In [107]:
E_max = 0
para_dict = {"gamma":0,"beta":0}
pbar = tqdm(total=len(beta_lst)*len(gamma_lst))
sim = Simulator('mqvector', 2)
C = QubitOperator('Z0 Z1') + QubitOperator('Z1') + QubitOperator('Z0')
H_c = Hamiltonian(C)
for i,beta in enumerate(beta_lst):
    for j,gamma in enumerate(gamma_lst):
        sim.reset()
        circuit = Circuit()
        circuit += H.on(0)
        circuit += H.on(1)
        circuit.barrier()
        circuit += ZZ('gamma_2').on((0,1))
        circuit += RZ('gamma_1').on(0)
        circuit += RZ('gamma_1').on(1)
        circuit.barrier()
        circuit += RX('beta').on(0)
        circuit += RX('beta').on(1)
        #circuit.measure_all()      
        sim.apply_circuit(circuit,pr = {"gamma_1":gamma,"gamma_2":gamma/2,"beta":beta})
        #sim.sampling(circuit)
        E = sim.get_expectation(H_c).real                       # 为线路中所有比特添加测量门
        #print("E_Max = {}, E = {}".format(E_max,E))
        if E > E_max:
            E_max = E
            para_dict["gamma"] = gamma
            para_dict["beta"] = beta
        else:
            pass
        pbar.update(1)
#sim.sampling(circuit, shots=1000).svg()

100%|█████████▉| 39930/40000 [00:23<00:00, 1707.55it/s]

100%|██████████| 40000/40000 [00:40<00:00, 1707.55it/s]

In [109]:
E_max

1.7776229267621906

In [108]:
para_dict

{'gamma': 4.104593416750483, 'beta': 1.2313780250251452}

In [132]:
sim.reset()
circuit = Circuit()
circuit += H.on(0)
circuit += H.on(1)
circuit.barrier()
circuit += ZZ('gamma_2').on((0,1))
circuit += RZ('gamma_1').on(0)
circuit += RZ('gamma_1').on(1)
circuit.barrier()
circuit += RX('beta').on(0)
circuit += RX('beta').on(1)
#sim.apply_circuit(circuit,pr = {"gamma_2":para_dict["gamma"]/2,"gamma_1":para_dict["gamma"], "beta":para_dict["beta"]})
#print(sim.get_qs(True))
circuit.measure_all() 
#sim.apply_circuit(circuit,pr = {"gamma":para_max[1], "beta":para_max[0]})
sim.sampling(circuit, pr = {"gamma_1":para_dict["gamma"],"gamma_2":para_dict["gamma"]/2,"beta":para_dict["beta"]},shots=100000).svg()


In [119]:
print(sim.get_qs())


[0.82567931+0.11251403j 0.16153393+0.02285447j 0.16153393+0.02285447j
 0.09810689+0.49268472j]


In [113]:
sim.get_qs(True)

'1¦00⟩'

In [133]:
circuit = Circuit()
circuit += H.on(0)
circuit += H.on(1)
circuit.barrier()
circuit += ZZ(para_dict["gamma"]/2).on((0,1))
circuit += RZ(para_dict["gamma"]).on(0)
circuit += RZ(para_dict["gamma"]).on(1)
circuit.barrier()
circuit += RX(para_dict["beta"]).on(0)
circuit += RX(para_dict["beta"]).on(1)

In [135]:
circuit.matrix()

array([[ 0.11939634-0.82459358j,  0.0344595 -0.15904434j,
         0.0344595 -0.15904434j,  0.49265665-0.1005696j ],
       [ 0.19118184-0.26209582j, -0.78259045-0.0547731j ,
         0.106245  +0.40345342j, -0.3243933 +0.00370164j],
       [ 0.19118184-0.26209582j,  0.106245  +0.40345342j,
        -0.78259045-0.0547731j , -0.3243933 +0.00370164j],
       [-0.30865498+0.00571015j, -0.28275363-0.32257907j,
        -0.28275363-0.32257907j,  0.06460532+0.72973413j]])